### ISSUE TITLE
使い方や画面の見方などの情報を運用していく場所を作りたい

### ISSUE THREAD

**Issue by dolow** [ClusterVR/CCKProcessTracer#4]
README で導入方法が示されていますが、使い方や画面の見方などの情報を追加できる場所があると、誰もがコントリビュートしやすくなると思いました。
どのような形の場が良さそうでしょうか？

e.g)
- github で管理されたマークダウンとして
- github Wiki
- 外部のブログサービスなど
- その他・・・

**Comment by masa-ibara** [comment]
今ぐらいの規模であればいったんReadmeで十分かなと思ったのですが、Wikiなど用意したほうがよいでしょうか

**Comment by dolow** [comment]
すぐに始められそうというのと、git (github) に閉じることができるので、他にこれというのがなければまずは README で良いと思います。
ボリューム増えてきたら考えましょうか。
