### ISSUE TITLE
Timerが影響を与える先がProcessTracer上で確認できない

### ISSUE THREAD

**Issue by simatten** [ClusterVR/CCKProcessTracer#6]
![スクリーンショット 2024-01-18 151120](https://github.com/ClusterVR/CCKProcessTracer/assets/71247602/02f7336b-c320-4b03-aa98-b625aa5a21fa)
↑のTimerが
![スクリーンショット 2024-01-18 151140](https://github.com/ClusterVR/CCKProcessTracer/assets/71247602/f0080dfb-9cd1-4a82-b7f2-15ec54f7232e)
↑のSignalを呼んでるはずだが、TimerにSignalがくっついていない
![スクリーンショット 2024-01-18 151232](https://github.com/ClusterVR/CCKProcessTracer/assets/71247602/c7811e99-f655-4c5a-bd5c-eeb2ad8df692)
↑のLogicへの矢印もない

本来はこのLogicがTimerの塊の右に来ていて、Timerの下に表示されるべきSignalから矢印が伸びていて欲しい

ItemTimerからリフレクションで値を取ってくる時に他のコンポーネントと勝手が違っててそのまま放置しちゃってたような気がするので、Timerの塊に値を持ってくることさえできれば解決しそう

**Comment by masa-ibara** [comment]
ITrigger,IGimmick,ILogicを複数同時に継承しているComponentを考慮できていなかった
